import type { Metadata } from "next";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
import { AgendaProvider } from "@/components/Elements/Context/AgendaContext";

export const metadata: Metadata = {
  title: "RPL_Final Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <AgendaProvider>{children}</AgendaProvider>
      </body>
    </html>
  );
}
